### ISSUE TITLE
Feature Request: use PreviousMap to resolve warning lines/columns

### ISSUE THREAD

**Issue by nicks** [postcss/postcss-reporter#20]
We use Less to compile .less files -> .css files, and then pass the css + sourcemap to postcss.

We have a formatter on top of postcss-reporter so that it resolves warnings against PreviousMap (https://github.com/postcss/postcss/blob/master/lib/previous-map.es6), back to the original .less files, rather than against the .css files.

Would you consider accepting this upstream? It's basically just a call to  `message.node.source.input.map.consumer().originalPositionFor({line: line, column: column})`

Thanks!

**Comment by davidtheclark** [comment]
Yes. 

Would we want to put it behind an option? Do you know how this works against regular CSS files, or, say, SCSS files that weren't compiled but were parsed with postcss-scss?

**Comment by nicks** [comment]
It would only change things if you pass a sourcemap in, or if the plugin adds its own sourcemap. I don't think postcss-scss uses sourcemaps at al.

Most users would probably want it on by default? Maybe for debugging you would want to turn it off, but then you would omit the sourcemap.

I'll send a PR.

**Comment by davidtheclark** [comment]
@nicks: It may be that I could have done this more gracefully with git ... but let me explain:

The PR looked great. In 34905fe808c281e3b134b508e08f7ffc3fa11a8e I cleaned up the util a little so it was more readable for me and tried to create a Less integration test so that I could see it working for real. 

My integration test seems to work, except I'm noticing that there at no columns being reported. The `nodeInput.origin()` call is returning a column of `0` in the Less file, when that should be `1`. Do you know what's going on? Or do you think there's any way the integration test can be improved?

**Comment by nicks** [comment]
Hmmm...your test looks reasonable to me. It might just be a limitation of the source maps generated by Less? It's been a while since I read up on the details of source maps, and how they're supposed to deal with column granularity.

**Comment by davidtheclark** [comment]
Ok, well I'll get a release out and we'll see if bugs pop up.

**Comment by davidtheclark** [comment]
Published in 1.3.2
